boards/urls.py
from django.urls import path

from . import views

app_name = 'boards'
urlpatterns = [
    path('', views.home, name='home'),
    path('<int:board_pk>/', views.board_topics, name='board_topics'),
    path('<int:board_pk>/new/', views.new_topic, name='new_topic'),
    path('<int:board_pk>/topics/<int:topic_pk>/', views.topic_posts, name='topic_posts'),
    path('<int:board_pk>/topics/<int:topic_pk>/reply/', views.reply_topic, name='reply_topic'),
]

config/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('accounts/', include('registration.urls')),
    path('boards/', include('boards.urls')),
    path('admin/', admin.site.urls),
]

myproject/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('boards/', include('boards.urls')),
    path('admin/', admin.site.urls),
]

registration/urls.py
from django.urls import include, path

from . import views

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('', include('django.contrib.auth.urls')),
]

boards/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import Truncator


class Board(models.Model):
    name = models.CharField(max_length=30, unique=True)
    description = models.CharField(max_length=100)

    def __str__(self):
        return self.name

    def get_posts_count(self):
        return Post.objects.filter(topic__board=self).count()

    def get_last_post(self):
        return Post.objects.filter(topic__board=self).order_by('-created_at').first()


class Topic(models.Model):
    subject = models.CharField(max_length=255)
    last_updated = models.DateTimeField(auto_now_add=True)
    board = models.ForeignKey(Board, on_delete=models.CASCADE, related_name='topics')
    starter = models.ForeignKey(User, on_delete=models.CASCADE, related_name='topics')
    views = models.PositiveIntegerField(default=0)
    
    def __str__(self):
        return self.subject


class Post(models.Model):
    message = models.TextField(max_length=4000)
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE, related_name='posts')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(null=True)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name='posts')
    updated_by = models.ForeignKey(User, on_delete=models.CASCADE, null=True, related_name='+')

    def __str__(self):
        truncated_message = Truncator(self.message)
        return truncated_message.chars(30)

boards/forms.py
from django import forms
from .models import Topic, Post

class NewTopicForm(forms.ModelForm):
    message = forms.CharField(
        widget=forms.Textarea(
            attrs={'rows': 5, 'placeholder': 'What is on your mind?'}
        ),
        max_length=4000,
        help_text='The max length of the text is 4000.'
    )
    
    class Meta:
        model = Topic
        fields = ['subject', 'message',]


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['message',]

boards/views.py
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.db.models import Count
from django.shortcuts import render, redirect, get_object_or_404
from .forms import NewTopicForm, PostForm
from .models import Board, Topic, Post

def home(request):
    boards = Board.objects.all()
    return render(request, 'boards/home.html', {'boards': boards})

def board_topics(request, board_pk):
    board = get_object_or_404(Board, pk=board_pk)
    topics = board.topics.order_by('-last_updated').annotate(replies=Count('posts') - 1)
    return render(request, 'boards/topics.html', {'board': board, 'topics':topics})

@login_required
def new_topic(request, board_pk):
    board = get_object_or_404(Board, pk=board_pk)
    if request.method == 'POST':
        form = NewTopicForm(request.POST)
        if form.is_valid():
            topic = form.save(commit=False)
            topic.board = board
            topic.starter = request.user
            topic.save()
            post = Post.objects.create(
                message=form.cleaned_data.get('message'),
                topic=topic,
                created_by=request.user
            )
            return redirect('boards:board_topics', board_pk=board_pk)
    else:
        form = NewTopicForm()
    return render(request, 'boards/new_topic.html', {'board': board, 'form': form})

def topic_posts(request, board_pk, topic_pk):
    topic = get_object_or_404(Topic, board__pk=board_pk, pk=topic_pk)
    topic.views += 1
    topic.save()
    return render(request, 'boards/topic_posts.html', {'topic': topic})

@login_required
def reply_topic(request, board_pk, topic_pk):
    topic = get_object_or_404(Topic, board__pk=board_pk, pk=topic_pk)
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.topic = topic
            post.created_by = request.user
            post.save()
            return redirect('boards:topic_posts', board_pk=board_pk, topic_pk=topic_pk)
    else:
        form = PostForm()
    return render(request, 'boards/reply_topic.html', {'topic': topic, 'form': form})

boards/templates/boards/home.html
{% extends 'boards/base.html' %}

{% block breadcrumb %}
    <li class="breadcrumb-item active" aria-current="page">Boards</li>
{% endblock %}

{% block content %}
    <table class="table table-dark">
        <thead>
            <tr>
                <th scope="col">Board</th>
                <th scope="col">Posts</th>
                <th scope="col">Topics</th>
                <th scope="Postseasocol">Last Post</th>
            </tr>
        </thead>
        <tbody>
            {% for board in boards %}
                <tr>
                    <td>
                        <a href="{% url 'board_topics' board.pk %}">{{ board.name }}</a>
                        <small class="text-muted d-block">{{ board.description }}</small>
                    </td>
                    <td class="align-middle">0</td>
                    <td class="align-middle">0</td>
                    <td></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

boards/templates/boards/includes/form.html
{% load widget_tweaks %}

{% for field in form %}
    <div class="form-group">
        {{ field.label_tag }}

        {% if form.is_bound %}
            {% if field.errors %}
                {% render_field field class="form-control is-invalid" %}
                {% for error in field.errors %}
                    <div class="invalid-feedback">
                        {{ error }}
                    </div>
                {% endfor %}
            {% else %}
                {% render_field field class="form-control is-valid" %}
            {% endif %}
        {% else %}
            {% render_field field class="form-control" %}
        {% endif %}

        {% if field.help_text %}
            <small class="form-text text-muted">
            {{ field.help_text }}
            </small>
        {% endif %}
    </div>
{% endfor %}

boards/templates/boards/topics.html
{% extends 'boards/base.html' %}

{% block title %}
    {{ board.name }} - {{ block.super }}
{% endblock %}

{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{% url 'home' %}">Boards</a></li>
    <li class="breadcrumb-item active" aria-current="page">{{ board.name }}</li>
{% endblock %}

{% block content %}
    <div class="mb-4">
        <a href="{% url 'new_topic' board.pk %}" class="btn btn-primary">New topic</a>
    </div>
    
    <table class="table table-dark">
        <thead>
            <tr>
                <th scope="col">Topic</th>
                <th scope="col">Starter</th>
                <th scope="col">Replies</th>
                <th scope="col">Views</th>
                <th scope="Postseasocol">Last Update</th>
            </tr>
        </thead>
        <tbody>
            {% for topic in board.topics.all %}
                <tr>
                    <td>{{ topic.subject }}</td>
                    <td>{{ topic.starter.username }}</td>
                    <td>0</td>
                    <td>0</td>
                    <td>{{ topic.last_updated }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

templates/base.html
{% load static %}

<!doctype html>
<html lang="ja">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap CSS -->
        <title>{% block title %}Django Boards{% endblock %}</title>
        <link href="https://fonts.googleapis.com/css?family=Srisakdi:700" rel="stylesheet">
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        {% block stylesheet %}{% endblock %}
    </head>
    <body>
        {% block body %}
        <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
            <div class="container">
                <a class="navbar-brand" href="{% url 'boards:home' %}">Django Boards</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#mainMenu" aria-controls="mainMenu" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="mainMenu">
                    {% if user.is_authenticated %}
                        <ul class="navbar-nav ml-auto">
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="userMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    {{ user.username }}
                                </a>
                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userMenu">
                                    <a class="dropdown-item" href="#">My account</a>
                                    <a class="dropdown-item" href="{% url 'password_change' %}">Change password</a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" href="{% url 'logout' %}">Log out</a>
                                </div>
                            </li>
                        </ul>
                    {% else %}
                        <form class="form-inline ml-auto">
                            <a href="{% url 'login' %}" class="btn btn-outline-secondary">Log in</a>
                            <a href="{% url 'signup' %}" class="btn btn-primary ml-2">Sign up</a>
                        </form>
                    {% endif %}
                </div>
            </div>
        </nav>

        <div class="container">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb my-4">
                    {% block breadcrumb %}
                    {% endblock %}
                </ol>
            </nav>

            {% block content %}
            {% endblock %}
        </div>
        {% endblock body %}

        <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
        <script src="{% static 'js/popper.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
    </body>
</html>

templates/boards/home.html
{% extends 'base.html' %}

{% load static %}

{% block stylesheet %}
    <link rel="stylesheet" href="{% static 'boards/css/boards.css' %}">
{% endblock %}

{% block breadcrumb %}
    <li class="breadcrumb-item active" aria-current="page">Boards</li>
{% endblock %}

{% block content %}
    <table class="table table-dark">
        <thead>
            <tr>
                <th scope="col">Board</th>
                <th scope="col">Posts</th>
                <th scope="col">Topics</th>
                <th scope="Postseasocol">Last Post</th>
            </tr>
        </thead>
        <tbody>
            {% for board in boards %}
                <tr>
                    <td>
                        <a href="{% url 'boards:board_topics' board.pk %}">{{ board.name }}</a>
                        <small class="text-muted d-block">{{ board.description }}</small>
                    </td>
                    <td class="align-middle">{{ board.get_posts_count }}</td>
                    <td class="align-middle">{{ board.topics.count }}</td>
                    <td class="align-middle">
                        {% with post=board.get_last_post %}
                            {% if post %}
                                <small>
                                    <a href="{% url 'boards:topic_posts' board.pk post.topic.pk %}">
                                        By {{ post.created_by.username }} at {{ post.created_at }}
                                    </a>
                                </small>
                            {% else %}
                                <small class="text-muted">
                                    <em>No posts yet.</em>
                                </small>
                            {% endif %}
                        {% endwith %}
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

templates/boards/new_topic.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
    Start a New Topic
{% endblock %}

{% block stylesheet %}
    <link rel="stylesheet" href="{% static 'boards/css/boards.css' %}">
{% endblock %}

{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{% url 'boards:home' %}">Boards</a></li>
    <li class="breadcrumb-item"><a href="{% url 'boards:board_topics' board.pk %}">{{ board.name }}</a></li>
    <li class="breadcrumb-item active" aria-current="page">New topic</li>
{% endblock %}

{% block content %}
    <form method="post" novalidate>
        {% csrf_token %}
        {% include 'includes/form.html' %}
        <button type="submit" class="btn btn-success">Post</button>
    </form>
{% endblock %}

templates/boards/reply_topic.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
    Post a reply
{% endblock %}

{% block stylesheet %}
    <link rel="stylesheet" href="{% static 'boards/css/boards.css' %}">
{% endblock %}

{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{% url 'boards:home' %}">Boards</a></li>
    <li class="breadcrumb-item"><a href="{% url 'boards:board_topics' topic.board.pk %}">{{ topic.board.name }}</a></li>
    <li class="breadcrumb-item"><a href="{% url 'boards:topic_posts' topic.board.pk topic.pk %}">{{ topic.subject }}</a></li>
    <li class="breadcrumb-item active">Post a reply</li>
{% endblock %}

{% block content %}
    <form method="post" novalidate class="mb-4">
        {% csrf_token %}
        {% include 'includes/form.html' %}
        <button type="submit" class="btn btn-success">Post a reply</button>
    </form>

    {% for post in topic.posts.all %}
        <div class="card mb-2">
            <div class="card-body p-3">
                <div class="row mb-3">
                    <div class="col-6">
                        <strong class="text-muted">{{ post.created_by.username }}</strong>
                    </div>
                    <div class="col-6 text-right">
                        <small class="text-muted">{{ post.created_at }}</small>
                    </div>
                </div>
                {{ post.message }}
            </div>
        </div>
    {% endfor %}
{% endblock %}

templates/boards/topic_posts.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
    {{ topic.subject }}
{% endblock %}

{% block stylesheet %}
    <link rel="stylesheet" href="{% static 'boards/css/boards.css' %}">
{% endblock %}

{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{% url 'boards:home' %}">Boards</a></li>
    <li class="breadcrumb-item"><a href="{% url 'boards:board_topics' topic.board.pk %}">{{ topic.board.name }}</a></li>
    <li class="breadcrumb-item active" aria-current="page">{{ topic.subject }}</li>
{% endblock %}

{% block content %}
    <div class="mb-4">
        <a href="{% url 'boards:reply_topic' topic.board.pk topic.pk %}" class="btn btn-primary" role="button">Reply</a>
    </div>

    {% for post in topic.posts.all %}
        <div class="card mb-2 {% if forloop.first %}border-dark{% endif %}">
            {% if forloop.first %}
                <div class="card-header text-white bg-dark py-2 px-3">{{ topic.subject }}</div>
            {% endif %}
            <div class="card-body p-3">
                <div class="row">
                    <div class="col-2">
                        <img src="{% static 'boards/img/avatar.png' %}" alt="{{ post.created_by.username }}" class="w-100">
                        <small>Posts: {{ post.created_by.posts.count }}</small>
                    </div>

                    <div class="col-10">
                        <div class="row mb-3">
                            <div class="col-6">
                                <strong class="text-muted">{{ post.created_by.username }}</strong>
                            </div>
                            <div class="col-6 text-right">
                                <small class="text-muted">{{ post.created_at }}</small>
                            </div>
                        </div>
                        {{ post.message }}
                        {% if post.created_by == user %}
                            <div class="mt-3">
                                <a href="#" class="btn btn-primary btn-sm" role="button">Edit</a>
                            </div>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
{% endblock %}

templates/boards/topics.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
    {{ board.name }} - {{ block.super }}
{% endblock %}

{% block stylesheet %}
    <link rel="stylesheet" href="{% static 'boards/css/boards.css' %}">
{% endblock %}

{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{% url 'boards:home' %}">Boards</a></li>
    <li class="breadcrumb-item active" aria-current="page">{{ board.name }}</li>
{% endblock %}

{% block content %}
    <div class="mb-4">
        <a href="{% url 'boards:new_topic' board.pk %}" class="btn btn-primary">New topic</a>
    </div>
    
    <table class="table table-dark">
        <thead>
            <tr>
                <th scope="col">Topic</th>
                <th scope="col">Starter</th>
                <th scope="col">Replies</th>
                <th scope="col">Views</th>
                <th scope="Postseasocol">Last Update</th>
            </tr>
        </thead>
        <tbody>
            {% for topic in topics %}
                <tr>
                    <td><a href="{% url 'boards:topic_posts' board.pk topic.pk %}">{{ topic.subject }}</td>
                    <td>{{ topic.starter.username }}</td>
                    <td>{{ topic.replies }}</td>
                    <td>{{ topic.views }}</td>
                    <td>{{ topic.last_updated }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

templates/includes/form.html
{% load widget_tweaks %}

{% if form.non_field_errors %}
    <div class="alert alert-danger" role="alert">
        {% for error in form.non_field_errors %}
            <p{% if forloop.last %} class="mb-0"{% endif %}>{{ error }}</p>
        {% endfor %}
    </div>
{% endif %}

{% for field in form %}
    <div class="form-group">
        {{ field.label_tag }}

        {% if form.is_bound %}
            {% if field.errors %}
                {% render_field field class="form-control is-invalid" %}
                {% for error in field.errors %}
                    <div class="invalid-feedback">
                        {{ error }}
                    </div>
                {% endfor %}
            {% else %}
                {% render_field field class="form-control is-valid" %}
            {% endif %}
        {% else %}
            {% render_field field class="form-control" %}
        {% endif %}

        {% if field.help_text %}
            <small class="form-text text-muted">
            {{ field.help_text }}
            </small>
        {% endif %}
    </div>
{% endfor %}